### PR TITLE
[libsparql] Fix build reproducibility. JB#58795

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
I wasn't able to reproduce the issue, tried both in a branch on OBS and locally. Still from the recent build log on OBS it's clear it's there. So I am really just guessing with the fix.

**Comment by pvuorela** [comment]
Wonder if this should be the same syncqt as qtbase has, e.g. if this is some ancient version of it.

**Comment by martyone** [comment]
Yes, they visibly have the same origin, but diverged a lot. The qtbase version also does sort every readdir output.

**Comment by pvuorela** [comment]
Mainly pondering if the qtbase version should be just synced here. Here there's been only one bigger commit for qt4/qt5 variants which maybe isn't needed anymore.

But the sorting also brings this slightly closer to qtbase so I'll just approve already.

**Review by pvuorela — APPROVED** [review]

**Comment by martyone** [comment]
Given the differences between this and qtbase's version and that the whole tree here is mostly a 2011 code, I am skeptical about the "just sync". If it works, don't touch it, right? :)

**Pull request merged**
